server:
  port: ${PORT:50101} #服务端口
spring:
  application:
    name: xc-service-eureka-server #指定服务名
eureka:
  client:
    registerWithEureka: true #服务注册，是否将自己注册到Eureka服务中
    fetchRegistry: true #服务发现，是否从Eureka中获取注册信息
    serviceUrl: #Eureka客户端与Eureka服务端的交互地址
      defaultZone: ${EUREKA_SERVER:http://eureka-dev-2:50102/eureka}
  server:
    enable-self-preservation: false #是否开启自我保护模式
    eviction-interval-timer-in-ms: 60000 #服务注册表清理间隔（单位毫秒，默认是60*1000）
  instance:
    hostname: ${EUREKA_DOMAIN:eureka-dev-1}
    prefer-ip-address: true

info:
  app.name: xc-service-eureka-server
  company.name: xuecheng education
  build.artifactId: com.xuecheng
  build.version: 1.0-SNAPSHOT