server:
  port: 31000
spring:
  application:
    name: xc-service-manage-cms-client

  #    MongoDB配置
  data:
    mongodb:
      uri:  mongodb://localhost:27017/xc_cms
      database: xc_cms

  #      FreeMarker配置
  freemarker:
    cache: false
    settings:
      template_update_delay: 0

  #        RibbitMQ配置
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    virtual-host: /
    port: 5672

    listener:
      direct:
        acknowledge-mode: manual
        consumers-per-queue: 1
        retry:
          enabled: true


#    默认队列设置
page:
  post:
    queue: queue_cms_postpage

#       Eureka Client Configuration
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER:http://eureka-dev-1:50101/eureka,http://eureka-dev-2:50102/eureka}
#  instance:
#    instance-id: ${spring.application.name}:${server.port}
#    prefer-ip-address: true
#
#
#info:
#    app.name: xc-service-manage-cms-client
#    company.name: xuecheng education
#    build.artifactId: com.xuecheng
#    build.version: 1.0-SNAPSHOT
